apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo3
  namespace: demo-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-demo3
  template:
    metadata:
      labels:
        app: nginx-demo3
    spec:
      containers:
        - name: nginx-demo3
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo3
  namespace: demo-gateway
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: nginx-demo3
  ports:
    - port: 80
      targetPort: 80
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: route-external-nginx-demo3
  namespace: demo-gateway
spec:
  parentRefs:
    - kind: Gateway
      name: external-http
      namespace: default
  hostnames:
    - 'nginx3.kanesa.xyz'
  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: nginx-demo3
          port: 80
