global:
  name: consul
  metrics:
    enabled: true

server:
  replicas: 1
  connect: true

connectInject:
  enabled: true
  transparentProxy:
    defaultEnabled: true

controller:
  enabled: true

client:
  enabled: true
  grpc: true

connect:
  enabled: true

ui:
  service:
    port:
      http: 8500
    annotations: |
      "cloud.google.com/neg": '{"ingress": true}'
